import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Search, LayoutDashboard, Radar, Users, Bookmark, FileText, Building2, GraduationCap, ShieldCheck, Bell, ChevronRight, MapPin, Footprints, Star, SlidersHorizontal, Plus, ArrowUpRight, Clock3, Target, Sparkles, Menu, X, ChevronDown } from 'lucide-react';
import './styles.css';

const players = [
  { id: 1, name: 'Rayo Pearce', age: 15, position: 'CAM', secondary: 'RW', foot: 'Right', country: 'South Africa', club: 'Liverpool Portland FC', location: 'Cape Town', fit: 94, status: 'Emerging', color: 'rp', traits: ['Vision', 'Control', 'Progression'], minutes: 1120, goals: 11, assists: 14, note: 'Creative attacking midfielder with strong spatial awareness and progression through the inside channels.' },
  { id: 2, name: 'Mandla Ndlovu', age: 18, position: 'RW', secondary: 'LW', foot: 'Left', country: 'South Africa', club: 'Cape United Academy', location: 'Johannesburg', fit: 91, status: 'Watchlist', color: 'mn', traits: ['1v1', 'Acceleration', 'Chance Creation'], minutes: 1380, goals: 13, assists: 9, note: 'Direct winger who consistently attacks the full-back and creates separation in transition.' },
  { id: 3, name: 'Thabo Maseko', age: 17, position: 'CM', secondary: 'CDM', foot: 'Right', country: 'South Africa', club: 'Soweto Football Academy', location: 'Soweto', fit: 89, status: 'Emerging', color: 'tm', traits: ['Scanning', 'Passing', 'Press Resistance'], minutes: 1510, goals: 6, assists: 12, note: 'Midfield connector with reliable circulation and strong awareness under pressure.' },
  { id: 4, name: 'Liam Jacobs', age: 19, position: 'CB', secondary: 'RB', foot: 'Right', country: 'South Africa', club: 'Bayhill United', location: 'Cape Town', fit: 87, status: 'Available', color: 'lj', traits: ['Aerial', 'Recovery', 'Build-up'], minutes: 1690, goals: 3, assists: 2, note: 'Athletic defender suited to a proactive line with improving distribution.' },
  { id: 5, name: 'Amani Okoro', age: 18, position: 'ST', secondary: 'LW', foot: 'Right', country: 'Nigeria', club: 'Lagos City Academy', location: 'Lagos', fit: 86, status: 'Emerging', color: 'ao', traits: ['Finishing', 'Movement', 'Athleticism'], minutes: 1295, goals: 17, assists: 6, note: 'Mobile striker who finds space between centre-back and full-back and attacks the box aggressively.' },
  { id: 6, name: 'Nia Daniels', age: 17, position: 'LB', secondary: 'LWB', foot: 'Left', country: 'Ghana', club: 'Accra Elite', location: 'Accra', fit: 84, status: 'Watchlist', color: 'nd', traits: ['Recovery', 'Crossing', 'Tempo'], minutes: 1432, goals: 2, assists: 11, note: 'Modern full-back with repeat running capacity and a progressive crossing profile.' }
];

const nav = [
  { key: 'dashboard', label: 'Overview', icon: LayoutDashboard },
  { key: 'discover', label: 'Discover Talent', icon: Radar },
  { key: 'players', label: 'Players', icon: Users },
  { key: 'shortlist', label: 'Shortlists', icon: Bookmark },
  { key: 'reports', label: 'Reports', icon: FileText }
];

function App() {
  const [page, setPage] = useState('dashboard');
  const [selected, setSelected] = useState(players[0]);
  const [query, setQuery] = useState('');
  const [position, setPosition] = useState('All positions');
  const [mobileOpen, setMobileOpen] = useState(false);
  const [shortlist, setShortlist] = useState([players[0].id, players[2].id]);
  const [reportOpen, setReportOpen] = useState(false);

  const filtered = useMemo(() => players.filter(p => {
    const text = `${p.name} ${p.position} ${p.country} ${p.club} ${p.location}`.toLowerCase();
    return text.includes(query.toLowerCase()) && (position === 'All positions' || p.position === position);
  }), [query, position]);

  const toggleShortlist = (id) => setShortlist(s => s.includes(id) ? s.filter(x => x !== id) : [...s, id]);
  const navigate = (key) => { setPage(key); setMobileOpen(false); };

  return <div className="app-shell">
    <aside className={mobileOpen ? 'sidebar mobile-open' : 'sidebar'}>
      <div className="brand"><div className="brand-mark">WTS</div><div><div className="brand-name">WTS Scout</div><div className="brand-sub">Talent intelligence</div></div><button className="icon-btn mobile-close" onClick={() => setMobileOpen(false)}><X size={18}/></button></div>
      <div className="workspace"><div className="workspace-dot"/><div><div className="workspace-label">SCOUT WORKSPACE</div><div className="workspace-name">William April</div></div><ChevronDown size={15}/></div>
      <nav className="nav">{nav.map(item => { const Icon = item.icon; return <button key={item.key} className={page === item.key ? 'nav-item active' : 'nav-item'} onClick={() => navigate(item.key)}><Icon size={18}/><span>{item.label}</span>{item.key === 'shortlist' && <span className="nav-count">{shortlist.length}</span>}</button> })}</nav>
      <div className="nav-section">ORGANISATION</div>
      <nav className="nav"><button className="nav-item" onClick={() => navigate('clubs')}><Building2 size={18}/><span>Clubs</span></button><button className="nav-item" onClick={() => navigate('academy')}><GraduationCap size={18}/><span>Academy</span></button></nav>
      <div className="sidebar-footer"><div className="footer-row"><ShieldCheck size={17}/><span>Verified workspace</span></div><div className="profile-mini"><div className="avatar avatar-w">WA</div><div><div className="profile-name">William April</div><div className="profile-role">Scout administrator</div></div><ChevronRight size={15}/></div></div>
    </aside>
    <main className="main">
      <header className="topbar"><button className="icon-btn mobile-menu" onClick={() => setMobileOpen(true)}><Menu size={20}/></button><div className="top-search"><Search size={17}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search players, clubs, positions..."/><span className="shortcut">⌘ K</span></div><div className="top-actions"><button className="icon-btn"><Bell size={18}/><span className="notif-dot"/></button><div className="top-divider"/><div className="avatar avatar-w">WA</div></div></header>
      {page === 'dashboard' && <Dashboard navigate={navigate} filtered={filtered} setSelected={setSelected} toggleShortlist={toggleShortlist} shortlist={shortlist}/>} 
      {page === 'discover' && <Discover filtered={filtered} query={query} setQuery={setQuery} position={position} setPosition={setPosition} setSelected={setSelected} toggleShortlist={toggleShortlist} shortlist={shortlist}/>} 
      {page === 'players' && <Players players={players} setSelected={setSelected} toggleShortlist={toggleShortlist} shortlist={shortlist}/>} 
      {page === 'shortlist' && <Shortlist players={players.filter(p => shortlist.includes(p.id))} setSelected={setSelected} toggleShortlist={toggleShortlist}/>} 
      {page === 'reports' && <Reports setSelected={setSelected} setReportOpen={setReportOpen}/>} 
      {['clubs','academy'].includes(page) && <Placeholder title={page === 'clubs' ? 'Clubs' : 'Academy'} description={page === 'clubs' ? 'Club recruitment workspaces are ready for the next build phase.' : 'Academy development tracking is staged for the next build phase.'}/>} 
    </main>
    <PlayerDrawer player={selected} shortlist={shortlist} toggleShortlist={toggleShortlist} reportOpen={reportOpen} setReportOpen={setReportOpen}/>
  </div>
}

function Dashboard({ navigate, filtered, setSelected, toggleShortlist, shortlist }) {
  return <section className="content"><div className="hero"><div><div className="eyebrow"><span className="eyebrow-dot"/> SCOUT INTELLIGENCE</div><h1>Find the next player<br/><span>before everyone else.</span></h1><p>Search emerging talent across your scouting network, build evidence-backed shortlists and turn observations into clear recruitment reports.</p><div className="hero-actions"><button className="btn btn-primary" onClick={() => navigate('discover')}><Radar size={17}/> Discover talent</button><button className="btn btn-secondary" onClick={() => navigate('shortlist')}><Bookmark size={17}/> Open shortlist</button></div></div><div className="hero-visual"><div className="pitch-card"><div className="pitch-label">LIVE SCOUTING MAP</div><div className="pitch-lines"/><div className="pitch-player p1">10</div><div className="pitch-player p2">7</div><div className="pitch-player p3">8</div><div className="pitch-player p4">11</div><div className="pitch-marker">SCOUT VIEW</div></div></div></div>
  <div className="metric-grid"><Metric icon={Users} label="Players tracked" value="1,248" delta="+86 this month"/><Metric icon={Bookmark} label="Shortlisted" value={shortlist.length.toString().padStart(2,'0')} delta="2 need review"/><Metric icon={Target} label="Open briefs" value="07" delta="3 high priority"/><Metric icon={FileText} label="Reports ready" value="24" delta="+6 this week"/></div>
  <div className="section-head"><div><div className="eyebrow">MATCHED TALENT</div><h2>Players to watch</h2></div><button className="text-btn" onClick={() => navigate('discover')}>View all <ArrowUpRight size={15}/></button></div>
  <div className="player-grid">{filtered.slice(0,4).map(p => <PlayerCard key={p.id} player={p} setSelected={setSelected} shortlist={shortlist} toggleShortlist={toggleShortlist}/>)}</div>
  <div className="dashboard-bottom"><div className="intel-card"><div className="card-kicker"><Sparkles size={15}/> WTS MATCH ENGINE</div><h3>Build a recruitment brief in plain language.</h3><p>Describe the player you need. WTS Scout maps your brief to structured criteria so you can review relevant profiles faster.</p><button className="btn btn-dark" onClick={() => navigate('discover')}>Create a brief <ChevronRight size={16}/></button></div><div className="activity-card"><div className="section-head small"><div><div className="eyebrow">RECENT ACTIVITY</div><h3>Scout timeline</h3></div><Clock3 size={17}/></div><Activity time="10 min" title="Added Rayo Pearce to shortlist" sub="CAM · Liverpool Portland FC"/><Activity time="1 hr" title="Scouting report generated" sub="Thabo Maseko"/><Activity time="3 hr" title="New player matched" sub="Amani Okoro · 86% brief fit"/></div></div>
 </section>
}

function Discover({ filtered, query, setQuery, position, setPosition, setSelected, toggleShortlist, shortlist }) {
 return <section className="content"><div className="page-heading"><div><div className="eyebrow">RECRUITMENT SEARCH</div><h1>Discover talent</h1><p>Explore profiles and narrow your search using evidence-based player criteria.</p></div><button className="btn btn-primary"><Plus size={17}/> New recruitment brief</button></div>
 <div className="filter-panel"><div className="filter-search"><Search size={17}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search name, club, country..."/></div><select value={position} onChange={e => setPosition(e.target.value)}><option>All positions</option><option>CAM</option><option>RW</option><option>CM</option><option>CB</option><option>ST</option><option>LB</option></select><button className="filter-btn"><SlidersHorizontal size={16}/> More filters</button></div>
 <div className="result-bar"><span><strong>{filtered.length}</strong> players matched</span><span>Sorted by <strong>brief fit</strong> <ChevronDown size={14}/></span></div>
 <div className="discover-layout"><div className="results-list">{filtered.map(p => <SearchResult key={p.id} player={p} setSelected={setSelected} toggleShortlist={toggleShortlist} shortlisted={shortlist.includes(p.id)}/>)}</div><aside className="brief-card"><div className="card-kicker"><Sparkles size={15}/> ACTIVE BRIEF</div><h3>Creative U19 attacker</h3><p>Right-footed attacking player with strong chance creation, game understanding and current competitive minutes.</p><div className="brief-tags"><span>U19</span><span>Attacking</span><span>Right foot</span><span>Africa</span></div><div className="brief-line"><span>Current matches</span><strong>6 candidates</strong></div><button className="btn btn-secondary full">Edit brief</button></aside></div></section>
}

function Players({ players, setSelected, toggleShortlist, shortlist }) {
 return <section className="content"><div className="page-heading"><div><div className="eyebrow">TALENT DATABASE</div><h1>Players</h1><p>Your wider scouting network, ready for deeper profile review.</p></div><button className="btn btn-primary"><Plus size={17}/> Add player</button></div><div className="player-grid large">{players.map(p => <PlayerCard key={p.id} player={p} setSelected={setSelected} shortlist={shortlist} toggleShortlist={toggleShortlist}/>)}</div></section>
}

function Shortlist({ players, setSelected, toggleShortlist }) {
 return <section className="content"><div className="page-heading"><div><div className="eyebrow">RECRUITMENT PIPELINE</div><h1>My shortlist</h1><p>Players you've flagged for deeper observation and next-step action.</p></div></div>{players.length ? <div className="player-grid">{players.map(p => <PlayerCard key={p.id} player={p} setSelected={setSelected} shortlist={players.map(x=>x.id)} toggleShortlist={toggleShortlist}/>)}</div> : <EmptyState title="Your shortlist is empty" description="Add players from Discover Talent or the Players database."/>}</section>
}

function Reports({ setSelected, setReportOpen }) {
 return <section className="content"><div className="page-heading"><div><div className="eyebrow">SCOUTING OUTPUT</div><h1>Reports</h1><p>Evidence-led reports generated from your scouting observations.</p></div><button className="btn btn-primary" onClick={() => { setSelected(players[0]); setReportOpen(true); }}><FileText size={17}/> Generate report</button></div><div className="report-list"><ReportRow player={players[0]} status="Ready" setSelected={setSelected} setReportOpen={setReportOpen}/><ReportRow player={players[2]} status="Ready" setSelected={setSelected} setReportOpen={setReportOpen}/><ReportRow player={players[4]} status="Draft" setSelected={setSelected} setReportOpen={setReportOpen}/></div></section>
}

function Placeholder({ title, description }) { return <section className="content"><div className="empty-page"><div className="empty-icon"><Building2 size={24}/></div><div className="eyebrow">WTS SCOUT</div><h1>{title}</h1><p>{description}</p><button className="btn btn-primary">Continue build <ChevronRight size={16}/></button></div></section> }
function Metric({ icon: Icon, label, value, delta }) { return <div className="metric-card"><div className="metric-icon"><Icon size={17}/></div><div><div className="metric-label">{label}</div><div className="metric-value">{value}</div><div className="metric-delta">{delta}</div></div></div> }
function Activity({ time, title, sub }) { return <div className="activity-row"><div className="activity-dot"/><div><div className="activity-title">{title}</div><div className="activity-sub">{sub}</div></div><div className="activity-time">{time}</div></div> }
function PlayerCard({ player, setSelected, shortlist, toggleShortlist }) { return <article className="player-card" onClick={() => setSelected(player)}><div className={`player-photo ${player.color}`}><span>{player.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div className="photo-position">{player.position}</div></div><div className="player-card-body"><div className="player-card-top"><div><h3>{player.name}</h3><div className="player-meta">{player.age} · {player.country} · {player.club}</div></div><button className={shortlist.includes(player.id) ? 'save-btn saved' : 'save-btn'} onClick={e => { e.stopPropagation(); toggleShortlist(player.id); }}><Bookmark size={15}/></button></div><div className="trait-row">{player.traits.map(t=><span key={t}>{t}</span>)}</div><div className="player-card-foot"><span><MapPin size={13}/>{player.location}</span><span className="fit"><Star size={13}/> {player.fit}% fit</span></div></div></article> }
function SearchResult({ player, setSelected, toggleShortlist, shortlisted }) { return <button className="search-result" onClick={() => setSelected(player)}><div className={`result-avatar ${player.color}`}>{player.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div className="result-main"><div className="result-name">{player.name}<span>{player.status}</span></div><div className="result-meta">{player.position} / {player.secondary} · {player.age} · {player.club}</div><div className="result-traits">{player.traits.map(t=><em key={t}>{t}</em>)}</div></div><div className="result-score"><strong>{player.fit}%</strong><span>fit</span></div><button className={shortlisted ? 'mini-save active' : 'mini-save'} onClick={e => { e.stopPropagation(); toggleShortlist(player.id); }}><Bookmark size={15}/></button><ChevronRight size={18}/></button> }
function ReportRow({ player, status, setSelected, setReportOpen }) { return <div className="report-row"><div className={`result-avatar ${player.color}`}>{player.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div className="report-main"><strong>{player.name}</strong><span>{player.position} · {player.club}</span></div><span className={`status ${status.toLowerCase()}`}>{status}</span><span className="report-date">Updated today</span><button className="icon-btn" onClick={() => {setSelected(player); setReportOpen(true);}}><ArrowUpRight size={17}/></button></div> }
function EmptyState({ title, description }) { return <div className="empty-state"><div className="empty-icon"><Bookmark size={20}/></div><h3>{title}</h3><p>{description}</p></div> }
function PlayerDrawer({ player, shortlist, toggleShortlist, reportOpen, setReportOpen }) { if (!player) return null; return <aside className={reportOpen ? 'drawer open report-drawer' : 'drawer open'}><div className={`drawer-hero ${player.color}`}><div className="drawer-initials">{player.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div className="drawer-hero-copy"><span>PROFILE · {player.status.toUpperCase()}</span><h2>{player.name}</h2><p>{player.position} · {player.secondary} · {player.club}</p></div><button className="drawer-close" onClick={() => setReportOpen(false)}><X size={18}/></button></div><div className="drawer-body"><div className="fit-box"><div><span>BRIEF FIT</span><strong>{player.fit}%</strong></div><div className="fit-bar"><i style={{width:`${player.fit}%`}}/></div></div><div className="profile-stats"><div><span>AGE</span><strong>{player.age}</strong></div><div><span>FOOT</span><strong>{player.foot}</strong></div><div><span>MINUTES</span><strong>{player.minutes}</strong></div><div><span>G/A</span><strong>{player.goals + player.assists}</strong></div></div><div className="drawer-section"><div className="eyebrow">SCOUT SUMMARY</div><p className="summary">{player.note}</p></div><div className="drawer-section"><div className="eyebrow">KEY TRAITS</div><div className="trait-row large">{player.traits.map(t=><span key={t}>{t}</span>)}</div></div><div className="drawer-section"><div className="eyebrow">ACTION</div><div className="drawer-actions"><button className="btn btn-primary" onClick={() => setReportOpen(true)}><FileText size={16}/> {reportOpen ? 'Report open' : 'Generate report'}</button><button className={shortlist.includes(player.id) ? 'btn btn-secondary saved-wide' : 'btn btn-secondary'} onClick={() => toggleShortlist(player.id)}><Bookmark size={16}/> {shortlist.includes(player.id) ? 'Shortlisted' : 'Add shortlist'}</button></div></div>{reportOpen && <div className="generated-report"><div className="card-kicker"><Sparkles size={15}/> WTS SCOUT REPORT</div><h3>Recruitment snapshot</h3><p><strong>Profile:</strong> {player.position}-led creator with {player.fit}% fit against the active brief.</p><p><strong>Evidence:</strong> {player.minutes} minutes, {player.goals} goals and {player.assists} assists in the current dataset.</p><p><strong>Next observation:</strong> Review performance against high-intensity opponents and confirm consistency over another 2–3 matches.</p></div>}</div></aside> }

createRoot(document.getElementById('root')).render(<App />);
